//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Cheques = new HashSet<Cheque>();
            this.Expanses = new HashSet<Expanse>();
            this.InvoiceReceipts = new HashSet<InvoiceReceipt>();
            this.Purchases = new HashSet<Purchase>();
            this.SupplierReciepts = new HashSet<SupplierReciept>();
        }
    
        public int BankId { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> BankBalance { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Cheque> Cheques { get; set; }
        public virtual ICollection<Expanse> Expanses { get; set; }
        public virtual ICollection<InvoiceReceipt> InvoiceReceipts { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<SupplierReciept> SupplierReciepts { get; set; }
    }
}
