//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<int> RefId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
