//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Invoices = new HashSet<Invoice>();
            this.InvoiceReceipts = new HashSet<InvoiceReceipt>();
        }
    
        public int ShopId { get; set; }
        public string ShopCode { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CurrentBalanace { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<InvoiceReceipt> InvoiceReceipts { get; set; }
    }
}
