//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpanseType
    {
        public ExpanseType()
        {
            this.Expanses = new HashSet<Expanse>();
        }
    
        public int ExpanseTypeId { get; set; }
        public string ExpanseTypeCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Expanse> Expanses { get; set; }
    }
}
