//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Inventories = new HashSet<Inventory>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.Purchases = new HashSet<Purchase>();
            this.PurchaseTargets = new HashSet<PurchaseTarget>();
            this.StockPositions = new HashSet<StockPosition>();
        }
    
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> Scheme { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Measurement { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<PurchaseTarget> PurchaseTargets { get; set; }
        public virtual ICollection<StockPosition> StockPositions { get; set; }
    }
}
