//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPosition
    {
        public int StockPositionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> PurchaseQuanity { get; set; }
        public Nullable<decimal> SoldQuantity { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> Tonage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
