//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Purchases = new HashSet<Purchase>();
            this.SupplierReciepts = new HashSet<SupplierReciept>();
        }
    
        public int SupplierId { get; set; }
        public string SupplierCode { get; set; }
        public string Address { get; set; }
        public string SupplierName { get; set; }
        public Nullable<decimal> OpeningBalanace { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<SupplierReciept> SupplierReciepts { get; set; }
    }
}
